### ISSUE TITLE
Import S3 generics from rstantools rather than rstanarm

### ISSUE THREAD

**Issue by bgoodri** [seananderson/rrfields#5]
I believe you can import the relevant S3 generics (i.e. `posterior_linpred`) from the **rstantools** package rather than the **rstanarm** package. If that is not completely the case, let us know and we can probably move stuff. Installing **rstanarm** is a relatively big cost for people that are not actually using it to fit models.

**Comment by seananderson** [comment]
Thanks @bgoodri, I'll change that. I read the very helpful 'Guidelines for Developers of R Packages Interfacing with Stan' but apparently read **rstantools** as **rstanarm** every time. Didn't realize **rstantools** existed.

Thanks for your whole team's work on Stan!
